title: Silicon Discourses
author: Garrett Partenza
email: garrettpartenza@icloud.com

# social links
twitter_username: garrettpartenza # DO NOT include the @ character, or else the build will fail!
github_username:  garrett-partenza-us # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
